#!/usr/bin/env python3
# Emit the deterministic scale/vstep lookup tables as const C arrays for the
# GBA port, so they land in cartridge ROM (.rodata) instead of RAM.  On the
# desktop/SDL2/win32/wince/android backends the same tables are built at
# runtime into .bss (Gfx_BuildScaleTables in jb_gfx_tile.c, Gfx_BuildTexVStep
# in jb_track.c); on the GBA their combined ~267 KB will not fit in the 32 KB
# IWRAM the default gba.specs linker script uses for .bss, so JB_TABLES_ROM
# swaps those runtime builds for the const arrays this script generates.
#
# The values are bit-exact: every arithmetic step is forced through IEEE-754
# single precision (f32) to reproduce the ARM/desktop `float` computation
# exactly, so the ROM tables equal what the runtime build would have produced.
import argparse
import struct


def f32(x):
    return struct.unpack('<f', struct.pack('<f', float(x)))[0]


def build_vstep(rows, stride):
    # jb_track.c Gfx_BuildTexVStep: per row h, step = 100.0f/h accumulated,
    # stored floored, clamped to a minimum of 1.  Rows past k >= h stay 0.
    data = [0] * (rows * stride)
    for h in range(1, rows):
        step = f32(f32(100.0) / f32(h))
        acc = 0.0
        for k in range(h):
            acc = f32(acc + step)
            v = int(acc)
            if v < 1:
                v = 1
            data[h * stride + k] = v
    return data


def build_step(rows, stride, last_w, span):
    # jb_gfx_tile.c BuildStepTable: per width w, step = span/w accumulated,
    # each entry the delta (int)acc - (int)(acc - step).  k >= w stay 0.
    data = [0] * (rows * stride)
    for w in range(1, last_w + 1):
        step = f32(span / f32(w))
        acc = 0.0
        for k in range(w):
            acc = f32(acc + step)
            data[w * stride + k] = int(acc) - int(f32(acc - step))
    return data


def emit(out, name, size, values):
    assert len(values) == size, (name, len(values), size)
    out.append('const short %s[%d] = {' % (name, size))
    line = []
    for i, v in enumerate(values):
        line.append(str(v))
        if len(line) == 20:
            out.append('    ' + ','.join(line) + ',')
            line = []
    if line:
        out.append('    ' + ','.join(line) + (',' if len(values) else ''))
    out.append('};')
    out.append('')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', required=True)
    args = ap.parse_args()

    out = [
        '/* Generated by tools/gen_tables.py - do not edit.',
        '   Precomputed scale/vstep lookup tables in ROM for the GBA port',
        '   (JumpyBall.exe Game_Init 0x00011560 g_texVStep 0x00035238,',
        '   Gfx_CreateBackBuffer 0x00021698 span 100.0f/64.0f/44.0f). */',
        '',
    ]
    # jb_track.h: JB_TEX_VSTEP_ROWS 299, jb_consts.h: JB_TEX_VSTEP_STRIDE 300.
    emit(out, 'jb_tex_vstep', 299 * 300, build_vstep(299, 300))
    # jb_gfx_tile.c JB_T100_ROWS/STRIDE 200, last_w 199, span 100.0f.
    emit(out, 'jb_step100', 200 * 200, build_step(200, 200, 199, 100.0))
    # JB_T64_ROWS 64 / STRIDE 70, last_w 63, span 64.0f.
    emit(out, 'jb_step64', 64 * 70, build_step(64, 70, 63, 64.0))
    # JB_T44_ROWS 50 / STRIDE 50, last_w 49, span 44.0f.
    emit(out, 'jb_step44', 50 * 50, build_step(50, 50, 49, 44.0))

    with open(args.out, 'w') as f:
        f.write('\n'.join(out))


if __name__ == '__main__':
    main()
